# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example

  express:
    image: node
    container_name: express
    volumes:
      - './Server:/Server'
      - '/Server/node_modules'
    command: bash -c "npm install --prefix /Server && npm run --prefix /Server"
    links:
      - 'db:database'

  frontend:
    image: node
    container_name: frontend
    volumes:
      - './client:/client'
      - '/client/node_modules'
    ports:
      - 5173:5173
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: bash -c "npm install --prefix /client && npm run dev --prefix /client -- --host"
    links:
      - 'express:express'
