# Use root/example as user/password credentials
version: "3.1"

services:
    express:
        image: node
        container_name: express
        ports:
            - 3000:3000
        volumes:
            - "./server:/server"
            - "/server/node_modules"
        command: bash -c "npm install --prefix /server && npm run dev --prefix /server"

    frontend:
        image: node
        container_name: frontend
        volumes:
            - "./client:/client"
            - "/client/node_modules"
        ports:
            - 5173:5173
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: bash -c "npm install --prefix /client && npm run dev --prefix /client -- --host"
        links:
            - "express:express"
