# Use root/example as user/password credentials
version: "3.1"

services:
    db:
        image: mysql
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - "/var/lib/mysql"
            - "./db-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"
            - "./db-scripts/dev.sql:/docker-entrypoint-initdb.d/2.sql"
            - "./db-scripts/testing.sql:/docker-entrypoint-initdb.d/3.sql"
        environment:
            - MYSQL_ROOT_PASSWORD=password
        healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 5s
            retries: 10

    express:
        image: node
        container_name: express
        ports:
            - 3000:3000
        volumes:
            - "./server:/server"
            - "/server/node_modules"
            - "./types:/types"
        command: bash -c "npm install --prefix /server && npm run dev --prefix /server"
        links:
            - "db:db"
        env_file:
            - "./config/db.dev.env"

    testing:
        build: .
        container_name: testing
        volumes:
            - "./server:/server"
            - "/server/node_modules"
            - "./types:/types"
            - "./test:/test"
            - "./client:/client"
            - "./db-scripts/reset-proc.sql:/reset-proc.sql"
            - "./db-scripts/store-proc.sh:/store-proc.sh"
        command: bash -c "/store-proc.sh && npm install --prefix /server && npm install --prefix /test && npm run test --prefix /test"
        links:
            - "db:db"
        env_file:
            - "./config/db.test.env"
        depends_on:
            db:
                condition: service_healthy

    frontend:
        image: node
        container_name: frontend
        volumes:
            - "./client:/client"
            - "/client/node_modules"
        ports:
            - 5173:5173
        stdin_open: true
        environment:
            - CHOKIDAR_USEPOLLING=true
        command: bash -c "npm install --prefix /client && npm run dev --prefix /client -- --host"
        links:
            - "express:express"
